
convert_dataset:
# 	pip install --upgrade datasets huggingface_hub
# 	hf auth login
# 	hf download --repo-type dataset randall-lab/cifar10-c --local-dir ./cifar10craw
# 	python convert.py
	hf upload --repo-type dataset robro/cifar10-c-parquet ./cifar10-c-parquet
