@weave_server=http://127.0.0.1:8080
@vec_server=http://localhost:9090

#############################
# Weaviate text2vec db

###
GET {{weave_server}}/v1/meta

###
GET {{weave_server}}/v1/schema

###
GET {{weave_server}}/v1/schema/Content

###
# View all object (add /id to limit)
GET {{weave_server}}/v1/objects

###
# Same as above but include the vectors
GET {{weave_server}}/v1/objects?include=vector

#########################
# Weaviate uses a different service to run the model
# this tests the other vector creating service

###
POST {{vec_server}}/vectors
Content-Type: application/json

{"text": "foo bar"}

